-- Desactivar temporalmente restricciones de clave foránea
ALTER TABLE Asignacion NOCHECK CONSTRAINT ALL;
ALTER TABLE Cliente NOCHECK CONSTRAINT ALL;
ALTER TABLE Empleado NOCHECK CONSTRAINT ALL;
ALTER TABLE Entrega NOCHECK CONSTRAINT ALL;
ALTER TABLE Pago NOCHECK CONSTRAINT ALL;
ALTER TABLE Pedido NOCHECK CONSTRAINT ALL;
ALTER TABLE SeguimientoEstado NOCHECK CONSTRAINT ALL;

-- 1. Eliminar datos en orden correcto
DELETE FROM Asignacion;
DELETE FROM Cliente;
DELETE FROM Empleado;
DELETE FROM Entrega;
DELETE FROM Pago;
DELETE FROM Pedido;
DELETE FROM SeguimientoEstado;

-- 2. Reiniciar IDENTITY en cada tabla
DBCC CHECKIDENT ('Asignacion', RESEED, 0);
DBCC CHECKIDENT ('Cliente', RESEED, 0);
DBCC CHECKIDENT ('Empleado', RESEED, 0);
DBCC CHECKIDENT ('Entrega', RESEED, 0);
DBCC CHECKIDENT ('Pago', RESEED, 0);
DBCC CHECKIDENT ('Pedido', RESEED, 0);
DBCC CHECKIDENT ('SeguimientoEstado', RESEED, 0);

-- 3. Activar nuevamente las restricciones
ALTER TABLE Asignacion CHECK CONSTRAINT ALL;
ALTER TABLE Cliente CHECK CONSTRAINT ALL;
ALTER TABLE Empleado CHECK CONSTRAINT ALL;
ALTER TABLE Entrega CHECK CONSTRAINT ALL;
ALTER TABLE Pago CHECK CONSTRAINT ALL;
ALTER TABLE Pedido CHECK CONSTRAINT ALL;
ALTER TABLE SeguimientoEstado CHECK CONSTRAINT ALL;